import { Inter } from "next/font/google";
import './style/basic.css'
import Header from "./reusables/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
      </body>
    </html>
  );
}
